/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BasicDemo01 */

#ifndef _Included_BasicDemo01
#define _Included_BasicDemo01
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BasicDemo01
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_BasicDemo01_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
