/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BasicDemo02 */

#ifndef _Included_BasicDemo02
#define _Included_BasicDemo02
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BasicDemo02
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BasicDemo02_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
